<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>AdManager.Web</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="8.0.31" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AdManager.Application\AdManager.Application.csproj" />
    <ProjectReference Include="..\AdManager.Infrastructure.Ad\AdManager.Infrastructure.Ad.csproj" />
    <ProjectReference Include="..\AdManager.Infrastructure.Exchange\AdManager.Infrastructure.Exchange.csproj" />
    <ProjectReference Include="..\AdManager.Infrastructure.Data\AdManager.Infrastructure.Data.csproj" />
    <ProjectReference Include="..\AdManager.Infrastructure.Automation\AdManager.Infrastructure.Automation.csproj" />
  </ItemGroup>
</Project>
